version: '2'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:9090 -t public public/index.php
        environment:
            docker: "true"
        ports:
            - 9090:9090
        volumes:
            - .:/var/www
            - logs:/var/www/logs
